### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sourya** [ramrodo/gobridge-mentorship#2]
- [ ] Benchmark for large amount of data
- [ ] Improve performance in-memory (AVL tree)
- [ ] Make data persist
- [ ] Use a better protocol to send data to server
- [ ] Build a CLI
